/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CrudJava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Janela classUnderTest = new Janela();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
